version: "3.7"
services:
  postgres:
    image: postgres:14
    container_name: antiFraudDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlos@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - postgres
    ports:
      - '5050:80'
  redis:
    image: redis:6.2-alpine
    container_name: myRedis
    restart: always
    ports:
      - '6379:6379'
    comand: redis-server --loglevel warning --requierepass debuggeandoideas