service: tokenization-ts

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    NODE_ENV: dev
  vpc:
    securityGroupIds:
      - sg-06ee66804ae96e883
    subnetIds:
      - subnet-05ffab68af51128c3
      - subnet-045822eb223153bb5
      - subnet-07dce99c0fc2feb01
      - subnet-0ea2eefd103d2eced
      - subnet-05873a4d30830bafb
      - subnet-0118e8b5d4b1fbe96
# custom:
#   POSTGRESQL:
#     HOST:
#       Fn::GetAtt: [PostgreSqlRDSInstance, database-2.chzoewnvixcm.us-east-1.rds.amazonaws.com]
#     PORT:
#       Fn::GetAtt: [PostgreSqlRDSInstance, 5432]
plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-offline-redis-server

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  tokenization:
    handler: app/handler.tokenization
    events:
      - http:
          path: tokenization
          method: POST
  findData2:
    handler: app/handler.findData
    events:
      - http:
          path: findData/{token}
          method: GET
